name:
  Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # 1: Code Checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      # 2: Setup Java
      - name: Setup JDK 17
        id: setup_jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3: Caching Gradle Packages
      - uses: actions/cache@v3
        name: Cache Gradle for quicker builds
        id: caching_gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5: Build Gradle
      - name: Build with Gradle
        run: ./gradlew build