name:
  Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # 1: Code Checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      # 2: Setup Java
      - name: Setup JDK 17
        id: setup_jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #4: Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 5: Build Gradle
      - name: Build with Gradle
        run: ./gradlew build

      #6: Upload Artifact
      - name: Uploading artifact to the build dir
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs